### ISSUE TITLE
Adding content when menu is collapsed causes it to become unresponsive

### ISSUE THREAD

**Issue by Fitzpasd** [google/hover#34]
I've uploaded a sample app that displays the issue [here]( https://github.com/Fitzpasd/hoverbug).

Changing content and notifying the listeners causes the collapsed menu to move to the top of the screen and become unresponsive.  

I've a fix for this issue which I'll submit for PR.

**Comment by Fitzpasd** [comment]
![before](https://cloud.githubusercontent.com/assets/1279954/24337734/c0d917fe-1254-11e7-9468-f278214e2f8e.jpg)

Initial state of menu.  Works as expected.

![after](https://cloud.githubusercontent.com/assets/1279954/24337750/e3b16182-1254-11e7-8c32-c3692a298142.jpg)

Press 'add content':  Menu moves to top right corner, and no long responds to input

**Comment by matthew-carroll** [comment]
I'm not sure if your fix survived the refactor or not.  If you see this issue or a similar one recur in 0.9.8, please re-open this issue.  Thanks.
