### ISSUE TITLE
How to keep hover active when app is closed ?

### ISSUE THREAD

**Issue by ZetDeveloper** [google/hover#37]
How to keep hover active when app is closed ?

**Comment by jahirfiquitiva** [comment]
@ZetDeveloper

You can use the [service](https://github.com/google/hover#subclass-hovermenuservice)

**Comment by ZetDeveloper** [comment]
@jahirfiquitiva iam usign service, but when close app, hover close and reestar hover alfer seconds.
iam keep hover open when user killed app.

**Comment by jahirfiquitiva** [comment]
@ZetDeveloper 
Well, yeah, it works like that for now (at least it does for me too). Anyways, it **does work** when app has been closed/killed.

**Comment by ZetDeveloper** [comment]
i'm fix mi problem:

add this code in HoverMenuService:

``Notification serviceNotification;;
   NotificationManager notificationManager;

    public void showNotification() {
        CharSequence tickerText = "asdads";
        CharSequence tickerContent = BuildConfig.VERSION_NAME;
        PendingIntent downloadManagerPendingIntent = PendingIntent.getActivity(this, 0, new Intent("android.intent.action.VIEW_DOWNLOADS").addFlags(1073741824).addFlags(67108864), 0);

        Application application = getApplication();
        getApplication();
        this.notificationManager = (NotificationManager) application.getSystemService(Context.NOTIFICATION_SERVICE);

        this.serviceNotification =  new NotificationCompat.Builder(this)
                .setSmallIcon(R.mipmap.ic_launcher)
                .setContentTitle("Hover active")
                .setContentText("1 tab")
                .setOngoing(false).setPriority(-2).build();
        startForeground(7524583, this.serviceNotification);
    }

and call showNotification in onCreate():

```@Override
    public void onCreate() {
        Log.d(TAG, "onCreate()");

        showNotification();

        mPrefs = getSharedPreferences(PREF_FILE, Context.MODE_PRIVATE);

        mHoverMenu = new HoverMenuBuilder(getContextForHoverMenu())
                .displayWithinWindow()
                .useNavigator(createNavigator())
                .useAdapter(createHoverMenuAdapter())
                .restoreVisualState(loadPreferredLocation())
                .build();
        mHoverMenu.addOnExitListener(mWindowHoverMenuMenuExitListener);
    }

**Comment by matthew-carroll** [comment]
If you would like your Hover menu to live outside of your main application then what you will need to do is have your Hover menu run in its own process.  That way it isn't tied to your main application process - your app can die and it won't effect your menu.
