### ISSUE TITLE
Empty Packages on Dependency Download

### ISSUE THREAD

**Issue by vontell** [google/hover#48]
When adding this library to my android project, gradle finishes the building and syncing tasks, but when I go to use the library, no classes are actually available. My IDE can see the packages and the R class, but everything else is missing. Any reason why this might occur?

**Comment by matthew-carroll** [comment]
I haven't heard of anything like this happening before.

Are you using the exact same Gradle compile line as shown in the README?

**Comment by vontell** [comment]
It seems as though this was an Android Studio problem, but I am not sure exactly what caused it (restarting Android Studio did not work, but waiting overnight apparently did!). It was also strange in that in my attempts to fix the issue, I forked the repo and hosted it using Jitpack, but that compile also resulted in the same issue. Anyhow, looks like Android Studio was the culprit (not surprising), and was not a problem with the library.
