### ISSUE TITLE
NavigatorContent showing behind tinted overlay

### ISSUE THREAD

**Issue by vontell** [google/hover#49]
I succeeded in having my menu pop up, and having navigator content appear. However, my NavigatorContent appears behind the tinted overlay, instead of on top of it at the same level as the tab. Any reason why this might occur? I am using a HoverMenuView within an activity, and create the HoverMenuView programmatically, adding it to the end of my `android.R.id.content` ViewGroup from my Activity.

**Comment by vontell** [comment]
Sorry about this, the NavigatorContent view needed to have an explicit white background

**Comment by fukemy** [comment]
hi bro, can u explain how did u ***done used  HoverMenuView within an activity,***? Im sucking with this
