### ISSUE TITLE
If screen orientation changed the hover button click failed

### ISSUE THREAD

**Issue by crossle** [google/hover#55]

**Comment by matthew-carroll** [comment]
Thanks for reporting the issue.  I have verified that the problem exists and I'll merge a fix into the develop branch.  The fix will be available with the next release.

**Comment by crossle** [comment]
Still have position issue, i use SingleSectionNotificationHoverMenuService demo

**Comment by mpa4hu** [comment]
Can confirm, is landscape mode hover becomes unresponsive

**Comment by matthew-carroll** [comment]
@crossle and @mpa4hu are you two having this issue on the "develop" branch or on the "master" branch?

**Comment by matthew-carroll** [comment]
My check on develop seems to show that this issue is resolved.  The fix will be available in the next release.  If you're having this problem on the "develop" branch then please re-open this ticket and describe the situation you're seeing.
