### ISSUE TITLE
EditText in content, keyboeard overlaying layout, params.softInputMode not affect

### ISSUE THREAD

**Issue by abselt** [google/hover#58]
if i use edittext in content layout it is not adjusting when keyboard open, which is not usable at all in a chat head particulary. I tried to edit WindowViewController with
`params.softInputMode = WindowManager.LayoutParams.SOFT_INPUT_STATE_HIDDEN`
with and without FLAG_NOT_FOCUSABLE  ..... with TYPE_PHONE and TYPE_SYSTEM_ALERT 
on addView and showView 
and in the content custom view
but nothing worked 
can you please suggest what should i do
and thanks

**Comment by abselt** [comment]
Sorry my fault, I thought I added compile project(':hover') in my gradle but it turn out that somehow i ctrl+z and i was still using the online lib.

**Comment by maituanmte** [comment]
Hi you,
I have a problem like that. Keyboard opens but layout not move. Please tell me how did you fix it?
