### ISSUE TITLE
Question: how to import to Android-Studio?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/hover#61]

**Comment by matthew-carroll** [comment]
What are you having trouble with, specifically?  Please re-open when you have actionable information.

**Comment by AndroidDeveloperLB** [comment]
Why do you close it before I have a chance to reply?
The issue is that I can't import it.
When I try, it makes the entire OS super slow, and never ends building. I've waited for more than 7 minutes, on a quite capable laptop, and it still doesn't finish. This is not acceptable.
Here's a screenshot:
![image](https://user-images.githubusercontent.com/5357526/33238179-5b3487ba-d290-11e7-9d98-1bf7b1863cc3.png)

**Comment by AndroidDeveloperLB** [comment]
I will try it at home too, on a brand new PC that I've bought, if you wish.

**Comment by matthew-carroll** [comment]
Which version of Android Studio are you using?

**Comment by AndroidDeveloperLB** [comment]
Actually, something was wrong just today with this laptop, as I tried Toshiba's "eco" mode. Made whole OS super slow. Not related to the repo.
I've disabled it, and now it works fine. Should have some stuff updated in the gradle files though:

![image](https://user-images.githubusercontent.com/5357526/33238285-5ed97d8c-d293-11e7-9e8e-c8d7392a881e.png)

Wonder what was the exact issue I had when I reported about this.

**Comment by matthew-carroll** [comment]
The build tools version will be upgraded in the next release.  The gradle version and build tools are rev'ing a lot right now with Android Studio.

**Comment by AndroidDeveloperLB** [comment]
reving?

**Comment by matthew-carroll** [comment]
Revisioning.  The versions are changing quite rapidly right now because of the work being done to go from Android Studio 2.x to Android Studio 3.x.  So Gradle versions and build tools versions will fall behind frequently for a while.

**Comment by AndroidDeveloperLB** [comment]
oh ok
