### ISSUE TITLE
Hover menu disappears when I move it to the top or bottom of the screen.

### ISSUE THREAD

**Issue by nguyenvuhuy** [google/hover#63]
As the title, it disappears without being retrievable, although the left and right sides of the screen work very well, thank you. Sorry about my English.

Video description:
https://youtu.be/fuzfx4zt9f4

**Comment by nguyenvuhuy** [comment]
I modified the source code, in the "InWindowDragger" file, I added the following code
`if (motionEvent.getRawY() > 100 && getMaxRawY() - motionEvent.getRawY() > 100) {`
`                                moveDragViewTo(mCurrentViewPosition);`
`                                mDragListener.onDragTo(mCurrentViewPosition.x, mCurrentViewPosition.y);`
` }`

and getMaxRawY() is:
` private Point mDisplaySize;`
 ` public int getMaxRawY() {`
`        if (mDisplaySize == null) {`
`            mDisplaySize = new Point();`
`            mWindowViewController.getWindowManager().getDefaultDisplay().getSize(mDisplaySize);`
`        }`
`        return mDisplaySize.y;`
`   }`

This is a trick and it seems to be not working smoothly when the user moves the "Hover menu", although it helps the user does not move the "Menu" to the outside of the screen. 
This is my temporary solution while waiting for the author of this library to fixed the bug. Thank you!

**Comment by since2014** [comment]
I've resolved this problem, [please check for the commit here](https://github.com/google/hover/pull/64/commits/d7a750c4a7f2daf50dbe5b2651e5cffaf511544f)

**Comment by nguyenvuhuy** [comment]
@since2014 Thank you so much! This works perfectly. You are a good contributor!

**Comment by matthew-carroll** [comment]
@since2014 and @nguyenvuhuy I addressed this issue by updating the logic in SideDock so that the dock position is always constrained within the top and bottom of the screen area.  The change for this issue will appear in the next release.
