### ISSUE TITLE
Issue when running demo

### ISSUE THREAD

**Issue by kumailn** [google/hover#67]
How can i fix the issue below:

java.lang.RuntimeException: Cannot obtain HoverThemeManager before calling init().

**Comment by matthew-carroll** [comment]
@kumailn please provide your full stack trace and also please describe what you did leading up to the crash.  I'm going to close the issue for now - you can re-open the issue when you have the additional information.

**Comment by akramul-hasan-m4** [comment]
@kumailn  Call   HoverThemeManager.init(Bus.getInstance(), new HoverTheme(getResources().getColor(R.color.colorPrimary), getResources().getColor(R.color.hover_shade_color)));
on your launcher activity- Oncreate . it is not a issue
