### ISSUE TITLE
Cannot close a single active session

### ISSUE THREAD

**Issue by brijeshshah13** [google/hover#70]
Currently Hover does not provide the support to close a single active section. If only a single section exists, then dismiss the Hover when the section is closed.

**Comment by matthew-carroll** [comment]
@brijeshshah13 I'm not quite sure what you mean by closing a session.  Can you describe exactly what is happening?

**Comment by brijeshshah13** [comment]
![inkedscreenshot_1511968389 - copy_li](https://user-images.githubusercontent.com/18366144/33383204-b13f4a4a-d548-11e7-8f13-5e132c70a96b.jpg)

For instance, only the circled session is to be closed by the user, then that's not possible as of now. Similarly, in the Hello World app, the following single session cannot be closed.
![inkedscreenshot_1511969191_li](https://user-images.githubusercontent.com/18366144/33383376-24c10760-d549-11e7-9d68-c54e3559dae1.jpg)

**Comment by matthew-carroll** [comment]
So those tabs are part of "sections" and you should be able add and remove sections without issue.  You can see a demo in the hello world app of sections being added and removed.  When there is a single section then it's unclear what the expected behavior of removing that section would be, so I don't know when or if I will add behavior for that.

**Comment by brijeshshah13** [comment]
The expected behavior of removing the last section must be the termination of the Hover itself. I would like to take up on that issue if you permit.

**Comment by mpa4hu** [comment]
You can implement such behavior yourself by checking if it a last section you are removing, then simply terminate the service. It should not be a default action

**Comment by brijeshshah13** [comment]
@matthew-carroll If it must not be a default action, you may now close the issue.
