### ISSUE TITLE
Hover Menu can't click and move after I rotate a screen

### ISSUE THREAD

**Issue by nguyenvuhuy** [google/hover#71]
- Like the title, I can not do how to be able to click and move it after I rotate the phone screen. I am looking forward to you can fix this, thank you very much!
Video description: https://www.youtube.com/watch?v=FeowYjSBv_M
(Sorry about my English)

##### There is another problem, I hope this feature you will add in the future

- When in landscape mode, it seems that the content display is relatively small, when the keyboard is displayed, it will cover the content. So, I'm really looking forward to you doing the content display like Messenger, thank you very much.

**1. Hover Menu**

![image](https://user-images.githubusercontent.com/30389595/33525402-68b9b280-d861-11e7-8c8c-8bbd004480b4.png)

**2. Messenger**
![image](https://user-images.githubusercontent.com/30389595/33525396-55011c60-d861-11e7-8815-2c4bb94ef5e9.png)

**Comment by matthew-carroll** [comment]
The issue of orientation change has been fixed on the develop branch and will be available in the next release.

As for your request about a different layout in landscape, please file a separate ticket for that so it can be tracked.
